### ISSUE TITLE
(1) Restart AppManager when ResourceLocked Exception is thrown [1.5]

### ISSUE THREAD

**Issue by klpanagi** [robotics-4-all/device-app-manager#16]
```
May 15 12:41:16 sythespi-2 app_manager.py[727]: pika.exceptions.ChannelClosedByBroker: (405, "RESOURCE_LOCKED - cannot obtain exclusive access to locked queue 'thing.device4.appmanager.install_app' in vhost '/'. It could be originally declared on another connection or the exclusive property value does not match that of the original declaration.")
```

**Comment by klpanagi** [comment]
Exceptions are raised in child threads, so this will need some serious development!!...
We need to implement a messaging mechanism between the main thread and child threads.

**Comment by klpanagi** [comment]
Latest push on [amqp-common-python](https://github.com/robotics-4-all/amqp-common-python) now supports external exception handling for this purpose. Before running an `RPC Server` it checks if it is already registered on the broker and raises an exception in that case.

```
[1590519689] - [Thing-AppManager] - [ERROR]: RPC <thing.device3.appmanager.is_alive> allready registered on broker.
Traceback (most recent call last):
  File "/home/klpanagi/development/r4a/device-app-manager/device_app_manager/app_manager.py", line 549, in run
    self._init_rpc_endpoints()
  File "/home/klpanagi/development/r4a/device-app-manager/device_app_manager/app_manager.py", line 294, in _init_rpc_endpoints
    raise exc
  File "/home/klpanagi/development/r4a/device-app-manager/device_app_manager/app_manager.py", line 286, in _init_rpc_endpoints
    self._init_isalive_rpc()
  File "/home/klpanagi/development/r4a/device-app-manager/device_app_manager/app_manager.py", line 305, in _init_isalive_rpc
    self._isalive_rpc.run_threaded()
  File "/home/klpanagi/development/r4a/amqp-common-python/amqp_common/rpc.py", line 104, in run_threaded
    raise ValueError(
ValueError: RPC <thing.device3.appmanager.is_alive> allready registered on broker.
```

So @iparaskev if you define a restart policy for the systemd service this should work after updating `amqp-common-python` to the latest on `master` branch.

**Comment by iparaskev** [comment]
@klpanagi The restart policy is already defined. And amqp has just been updated. :metal:

**Comment by klpanagi** [comment]
Damn it F#Works! :metal:

```
May 28 11:17:18 sythespi-2 systemd[1]: app_manager.service: Service RestartSec=100ms expired, scheduling restart.
May 28 11:17:18 sythespi-2 systemd[1]: app_manager.service: Scheduled restart job, restart counter is at 8.
```
