### ISSUE TITLE
Transform app_name to docker compatible format

### ISSUE THREAD

**Issue by klpanagi** [robotics-4-all/device-app-manager#2]
Must not:
- be hash
- have uppercase

**Comment by klpanagi** [comment]
Also...

```
[1586447874] - [urllib3.connectionpool] - [DEBUG]: http://localhost:None "POST /v1.35/build?t=testing+app&q=False&nocache=False&rm=True&forcerm=True&pull=False HTTP/1.1" 500 39             │·················································
[1586447874] - [Thing-AppManager] - [ERROR]: 500 Server Error: Internal Server Error ("invalid reference format")                                                                            │·················································
Traceback (most recent call last):                                                                                                                                                           │·················································
  File "/usr/local/lib/python3.7/dist-packages/docker/api/client.py", line 261, in _raise_for_status                                                                                         │·················································
    response.raise_for_status()                                                                                                                                                              │·················································
  File "/home/pi/.local/lib/python3.7/site-packages/requests/models.py", line 935, in raise_for_status                                                                                       │·················································
    raise HTTPError(http_error_msg, response=self)                                                                                                                                           │·················································
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.35/build?t=testing+app&q=False&nocache=False&rm=True&forcerm=True&pull=False      
```
