### ISSUE TITLE
App manager crash on ELSA startup

### ISSUE THREAD

**Issue by etsardou** [robotics-4-all/device-app-manager#27]
With error:
```
Ιουν 11 11:38:38 sythespi-2 app_manager.py[1134]: [1591871918] - [RpcServer-thing.device4.appmanager.apps.running] - [ERROR]: No activity or too many missed heartbeats in the last 60 seconds
Ιουν 11 11:38:38 sythespi-2 app_manager.py[1134]: Traceback (most recent call last):
Ιουν 11 11:38:38 sythespi-2 app_manager.py[1134]:   File "/home/pi/.local/lib/python3.7/site-packages/amqp_common/rpc.py", line 94, in run
Ιουν 11 11:38:38 sythespi-2 app_manager.py[1134]:     self._channel.start_consuming()
Ιουν 11 11:38:38 sythespi-2 app_manager.py[1134]:   File "/usr/local/lib/python3.7/dist-packages/pika/adapters/blocking_connection.py", line 1866, in start_consuming
Ιουν 11 11:38:38 sythespi-2 app_manager.py[1134]:     self._process_data_events(time_limit=None)
Ιουν 11 11:38:38 sythespi-2 app_manager.py[1134]:   File "/usr/local/lib/python3.7/dist-packages/pika/adapters/blocking_connection.py", line 2027, in _process_data_events
Ιουν 11 11:38:38 sythespi-2 app_manager.py[1134]:     self.connection.process_data_events(time_limit=time_limit)
Ιουν 11 11:38:38 sythespi-2 app_manager.py[1134]:   File "/usr/local/lib/python3.7/dist-packages/pika/adapters/blocking_connection.py", line 825, in process_data_events
Ιουν 11 11:38:38 sythespi-2 app_manager.py[1134]:     self._flush_output(common_terminator)
Ιουν 11 11:38:38 sythespi-2 app_manager.py[1134]:   File "/usr/local/lib/python3.7/dist-packages/pika/adapters/blocking_connection.py", line 522, in _flush_output
Ιουν 11 11:38:38 sythespi-2 app_manager.py[1134]:     raise self._closed_result.value.error
Ιουν 11 11:38:38 sythespi-2 app_manager.py[1134]: pika.exceptions.AMQPHeartbeatTimeout: No activity or too many missed heartbeats in the last 60 seconds
```

**Comment by klpanagi** [comment]
Seems to be issue with the systemd service runlevel target.
The systemd service should start after system runlevel3 has been reached... That should be the problem. Loading solution!... :metal:
